spring:
  application:
    name: itoken-eureka    #为服务端命名
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:                              #增加zipkin服务端地址
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost              #Eureka服务器的地址
  client:                            #若不将以下属性设置为false，会被当做客户端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:                       #配置访问Eureka服务器的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info